### ISSUE TITLE
Browserify bundle failing when requiring signalPayloadProvider and actionMutationsProvider

### ISSUE THREAD

**Issue by aesprice** [cerebral/cerebral-module-signal-store#6]
The errors I specifically get when trying to bundle my application is this:

```
Error : undefined
Cannot find module 'cerebral/providers/signalPayloadProvider' from '/Users/aprice/Projects/stem-py/node_modules/cerebral-module-devtools/node_modules/cerebral-module-signal-store'
Error : undefined
Cannot find module 'cerebral/providers/actionMutationsProvider' from '/Users/aprice/Projects/stem-py/node_modules/cerebral-module-devtools/node_modules/cerebral-module-signal-store'
```

Looking at the node_modules folder, `cerebral` just isn't there. And looking at the `package.json`, `cerebral` is not in `dependencies` (although it _is_ in `devDependencies` and `peerDependencies`).

I was not having this issue until this morning.

**Comment by Guria** [comment]
as mentioned on discord, just make sure you are running latest `cerebral@0.34.0-rc.4` or stable `cerebral@0.33.33`.
Signal store will not have cerebral in its node_modules, because it doesn't directly depend on it. it just uses one from your project dependency (see peerDependency)

**Comment by Guria** [comment]
ouch, can you tell which version of `cerebral` do you use? seems we really made 'signal-store' incompatible with 0.33 :(

**Comment by aesprice** [comment]
I've been using 0.33.31.

**Comment by Guria** [comment]
please define strict version of devtools to 0.6.3 and signal-store 0.1.7 (you will  have to define signal-store module in your package.json) until we will find a way to fix it

**Comment by aesprice** [comment]
Okay, I tried devtools@0.6.3 and signal-store@0.1.7, and that seems to have fixed things for now. I can successfully build my app and use devtools. Thanks for pointing me in the right direction.

**Comment by Guria** [comment]
`cerebral@0.33.34` is out to address this problem.

**Comment by saitodisse** [comment]
perfect @Guria its working now
